[package]
name = "yuma"
version = "0.1.1"
edition = "2021"

[dependencies]
yumadoc = { path = "../yumadoc" }
thiserror = "1"
anyhow = "1"

serde = {version = "1", features = ["derive"]}
serde_json = "1"
