[package]
name = "freight"
version = "0.1.0"
edition = "2021"

[dependencies]
# serde = { version = "1", features = ["derive"]}
# yaml = { package = "serde_yaml", version = "0.9" }
# syn = { version = "2", features = ["full", "extra-traits"]}

[[bin]]
name = "yuma"
path = "src/main.rs"
