#!/bin/sh

YUMACACHE="$HOME/.config/iyuma/.yumacache.json"

find_backend () {
    printf "paru"
}

pkg () {
    case "$backend" in
        "paru")
            bparu "$@"
        ;;
        "brew")
            bbrew "$@"
        ;;
        *)
            backend=$(find_backend)
            pkg
        ;;
    esac
}

usage () {
    echo "Freight - A code based package manager
freight [subcommand]

subcommands:
init
    create a new system declaration with sensible defaults

list
    list the installed packages

add 
    reserved word

help
    show this text"
}


case "$1" in
    "init") 
        cargo init
        echo "yuma = { package = \"yuma\", git = \"https://github.com/Focus172/freight.git\" }" >> Cargo.toml
    ;;
    "add")
        echo "todo!: add the thing to the file and rebuild"
    ;;
    "list")
        cat $YUMACACHE | jq '.enabled_packages' | tail +2 | head -n-1 | sed 's/  //g;s/"//g;s/,//g'
        ;;
    "help")
        usage
    ;;
    *)
        echo "Unknown Option: { $1 }"
        echo ""
        usage
        exit 1
    ;;
esac

